### ISSUE TITLE
AsciiCinema recording is archived

### ISSUE THREAD

**Issue by aleksandersumowski** [Invertisment/conjure-clj-additions-nrepl#2]

**Comment by Invertisment** [comment]
Oh right. Sorry.
I'll try to rerecord it and properly publish it. 
Thanks for reporting!

**Comment by Invertisment** [comment]
Updated in latest commit. This time the recording won't expire.

Link: https://asciinema.org/a/gttCs2OFslyjSmdDEVhw5DIh5
